/**
 * Finds price-history rows that look like testing leftovers rather than real
 * purchases, and (only when asked) deletes them.
 *
 * Nothing here guesses on your behalf: every row is printed with the reason
 * it was flagged, and deleting is a separate, explicit run.
 *
 * Usage:
 *   npm run db:audit-prices                  — report only, changes nothing
 *   npm run db:audit-prices -- --json        — same report as JSON
 *   npm run db:audit-prices -- --delete-orphans
 *   npm run db:audit-prices -- --delete-ids 41,57
 *
 * What gets flagged
 *   orphan     The list this price was recorded on has been deleted. Since
 *              recordPurchase() always stamps a listId, a null one can only
 *              mean a deleted list — i.e. a list made while testing. These
 *              are invisible in the app except as a nameless row in the
 *              price history.
 *   demo       Matches the SEED_DEMO fixture in prisma/seed.ts: one of the
 *              first ten catalogue items, at the seeder's formula price, for
 *              the seeder's quantity. Generated data, never typed by anyone.
 *   test-list  Recorded on a list whose name reads like a trial run
 *              ("test", "demo", "sample", ...).
 *   outlier    The item has three or more comparable prices and this one is
 *              4x off the median of the others — a slipped decimal or a
 *              number typed to see what the screen does.
 *   conflict   The item has exactly two comparable prices and they are 4x
 *              apart. Too little history to say which is wrong, so both are
 *              printed and you decide.
 *   rapid      Prices for the same item recorded on two different lists
 *              within ten minutes of each other — the signature of poking at
 *              the purchase sheet, not of shopping.
 */
import "dotenv/config";
import { createScriptClient } from "./master-import.js";
import {
  formatPrice,
  formatQty,
  formatUnitPrice,
  unitPriceOf,
  type UnitType,
} from "../src/lib/units.js";
import {
  DEMO_ITEM_COUNT,
  OUTLIER_FACTOR,
  RAPID_WINDOW_MINUTES,
  findSuspectRows,
  type Reason,
  type Row,
} from "./price-audit.js";

async function main() {
  const argv = process.argv.slice(2);
  const asJson = argv.includes("--json");
  const deleteOrphans = argv.includes("--delete-orphans");
  const idsFlag = argv.indexOf("--delete-ids");
  const deleteIds =
    idsFlag === -1
      ? []
      : (argv[idsFlag + 1] ?? "")
          .split(",")
          .map((part) => Number.parseInt(part.trim(), 10))
          .filter((id) => Number.isInteger(id));

  const prisma = createScriptClient();
  try {
    const raw = await prisma.priceHistory.findMany({
      orderBy: [{ itemId: "asc" }, { purchasedAt: "asc" }],
      include: {
        item: { select: { nameEn: true, nameTa: true } },
        shop: { select: { name: true } },
        list: { select: { name: true } },
      },
    });

    const rows: Row[] = raw.map((row) => {
      const price = Number(row.price);
      const quantity = Number(row.quantity);
      return {
        id: row.id,
        itemId: row.itemId,
        price,
        quantity,
        unitType: row.unitType as UnitType,
        purchasedAt: row.purchasedAt,
        itemName: `${row.item.nameTa} / ${row.item.nameEn}`,
        shopName: row.shop?.name ?? null,
        listName: row.list?.name ?? null,
        unitPrice: unitPriceOf(price, quantity, row.unitType as UnitType),
      };
    });

    // The seeder picks its items by position in the catalogue, so the same
    // ordering identifies them again.
    const demoItemIds = new Set(
      (
        await prisma.item.findMany({
          where: { isActive: true },
          orderBy: [{ categoryId: "asc" }, { id: "asc" }],
          take: DEMO_ITEM_COUNT,
          select: { id: true },
        })
      ).map((item) => item.id),
    );

    const flagged = findSuspectRows(rows, demoItemIds);

    if (asJson) {
      console.log(JSON.stringify({ total: rows.length, flagged }, null, 2));
    } else {
      console.log(`Price history rows: ${rows.length}`);
      console.log(`Suspect rows:       ${flagged.length}\n`);

      const order: Reason[] = ["orphan", "demo", "test-list", "outlier", "conflict", "rapid"];
      const heading: Record<Reason, string> = {
        orphan: "Recorded on a list that has since been deleted",
        demo: "Generated by the SEED_DEMO fixture",
        "test-list": "Recorded on a list named like a trial run",
        outlier: `More than ${OUTLIER_FACTOR}x off this item's usual price`,
        conflict: `Only two prices for this item, ${OUTLIER_FACTOR}x apart — check both`,
        rapid: `Entered within ${RAPID_WINDOW_MINUTES} minutes of another price for the same item`,
      };

      for (const reason of order) {
        const group = flagged.filter((row) => row.reasons.includes(reason));
        if (!group.length) continue;
        console.log(`${heading[reason]} — ${group.length}`);
        for (const row of group) {
          // Per kg / per L / each — the figure that makes a wrong price
          // obvious however the pack size was entered.
          const unitPrice = formatUnitPrice(row.price, row.quantity, row.unitType);
          const per = unitPrice === null ? "" : ` (${unitPrice})`;
          const also = row.reasons.filter((other) => other !== reason);
          console.log(
            `  #${row.id}  ${row.itemName}  ${formatPrice(row.price)} for ` +
              `${formatQty(row.quantity, row.unitType)}${per}  ` +
              `${row.shopName ?? "no shop"} · ${row.listName ?? "no list"} · ` +
              `${row.purchasedAt.toISOString().slice(0, 10)}` +
              (also.length ? `  [also: ${also.join(", ")}]` : ""),
          );
        }
        console.log("");
      }

      const orphans = flagged.filter((row) => row.reasons.includes("orphan"));
      if (orphans.length && !deleteOrphans && !deleteIds.length) {
        console.log(
          `Delete the ${orphans.length} orphaned row(s):  npm run db:audit-prices -- --delete-orphans`,
        );
        console.log(
          "Delete specific rows:              npm run db:audit-prices -- --delete-ids 41,57",
        );
      }
    }

    if (deleteOrphans) {
      const result = await prisma.priceHistory.deleteMany({
        where: { listId: null },
      });
      console.log(`\nDeleted ${result.count} orphaned row(s).`);
    }
    if (deleteIds.length) {
      const result = await prisma.priceHistory.deleteMany({
        where: { id: { in: deleteIds } },
      });
      console.log(`\nDeleted ${result.count} row(s) by id: ${deleteIds.join(", ")}`);
    }
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
